### PR TITLE
Suppress race condition warning in ffs_conv.c

### PR DESCRIPTION
**Pull request by KyleFromKitware**
Even though we're not using a proper lock for these lazy-initialized
variables, they are unlikely to cause a race condition, since their
value is deterministic. Suppress the warning, and also ensure that
_ffs_conversion_generation is only assigned once to avoid reading it
in an inconsistent state.

### CODE REVIEW

**Comment by KyleFromKitware** [comment]
This only protects the `ffs_conversion_generation` flag (and its sibling, `generation_verbose`), which appear to be lazy-initialized. (Is there some way to make these not global?)

**Comment by eisenhauer** [comment]
Yes, they are lazily initialized, but I think they need no protection.  Any thread that hits them will compute the same result for initialization.  If they do it simultaneously, it all comes out in the wash...  No need to add a mutex for this (except to silence warnings, and I think it's not worth adding a library dependency for that).

**Comment by KyleFromKitware** [comment]
The problem is that omitting the lock might leave the variables in an inconsistent state if one thread is initializing them while another calls the same method. Consider this code:

```c
    if (ffs_conversion_generation == -1) {
        char *gen_string = getenv("FFS_CONVERSION_GENERATION");
        ffs_conversion_generation = FFS_CONVERSION_GENERATION_DEFAULT;
        if (gen_string != NULL) {
#ifdef MODULE
            ffs_conversion_generation = strtol(gen_string, NULL, 10);
            if ((ffs_conversion_generation == LONG_MIN) ||
                (ffs_conversion_generation == LONG_MAX) || 
                (ffs_conversion_generation == 0)) {
#else
            if (sscanf(gen_string, "%d", &ffs_conversion_generation) != 1) {
#endif
                if (*gen_string == 0) {
                    /* empty string, just turn on generation */
                    ffs_conversion_generation = 1;
                } else {
                    printf("Unable to parse FFS_CONVERSION_GENERATION environment variable \"%s\".\n", gen_string);
                }
            }
        }
        debug_code_generation =
            (getenv("FFS_CONVERSION_DEBUG") != NULL);
        generation_verbose =
            (getenv("FFS_CONVERSION_VERBOSE") != NULL);
    }
```

Notice that `ffs_conversion_generation` gets set before `debug_code_generation` and `generation_verbose`, potentially leaving them in an inconsistent state when the second thread comes along. Sure, we could "fix" it by shifting the order around, but... modern compilers are very clever, and might re-order things in ways we don't expect, potentially putting it back in the "wrong" order.

A better alternative might be to forego caching and lazy initialization altogether, and parse the `getenv()`s each time (unless this function is called in a tight loop or other performance-sensitive area of code.) The problematic code is not very long, only ~20 lines.

**Comment by eisenhauer** [comment]
How about just giving debug_code_generation and generation_verbose their own protective if()?

**Comment by KyleFromKitware** [comment]
Better, but there's still the issue that `ffs_conversion_generation` gets assigned multiple times, potentially leaving it in an inconsistent state as well, which would potentially change whether or not the entire rest of the function gets executed.

**Comment by KyleFromKitware** [comment]
I suppose we could do the multiple assignments to a temporary variable, and only once we're sure of its value, *then* assign it to `ffs_conversion_generation` for real. That would most likely take care of 99% of potential issues with this code. (We will still need to add a suppression, though.)

**Comment by eisenhauer** [comment]
Baseline assumption:  getenv() results don't change.  We're not using putenv() and the possibility that the application is actively using putenv() to screw with us seems incredibly remote.  Assuming that getenv() results don't change, each assignment is deterministic.  So any thread that hits the if() will either see it uniniitalized, and initialize it itself with a deterministic value, or see it initialized to that deterministic value already...  Nobody gets out of the if with the value in an inconsistent state.

**Comment by KyleFromKitware** [comment]
> Baseline assumption: getenv() results don't change.

I absolutely agree, but that's not the problem. Consider this scenario:

1. Thread 1 runs the following, where `FFS_CONVERSION_GENERATION` is an empty string:

```c
            ffs_conversion_generation = strtol(gen_string, NULL, 10);
```

At this point, `ffs_conversion_generation` is `0`.

2. Thread 2 runs:

```c
    if (ffs_conversion_generation == -1) { // Skips over this block
        // ...
    }
    if (!ffs_conversion_generation) { // Returns because ffs_conversion_generation is 0
        pthread_mutex_unlock(&generation_mutex);
        return NULL;
    }
```

3. Thread 1 resumes execution and runs:

```c
                if (*gen_string == 0) {
                    /* empty string, just turn on generation */
                    ffs_conversion_generation = 1;
                } else {
                    printf("Unable to parse FFS_CONVERSION_GENERATION environment variable \"%s\".\n", gen_string);
                }
```

At this point, `ffs_conversion_generation` is `1` (the right answer), but thread 2 read it as `0` (the wrong answer).

This can be helped by doing the `getenv()` parsing on a temporary variable, and then assigning that to `ffs_conversion_generation` at the end.

**Comment by eisenhauer** [comment]
Sorry, I'm ignoring the #ifdef MODULE stuff.  This is truly ancient code from some research work where many of these packages were built as Linux kernel modules.  I've elided it in some places, but not everywhere.  But there's a similar problem on the sscanf() path, with the first assignment using FFS_CONVERSION_GENERATION_DEFAULT, followed by an assignment with the determined value which might indeed be different.  The window is the duration of the sscanf() at least.  So yes, a temporary seems the way to go so that there's just a single assignment to ffs_conversion_generation.

**Comment by KyleFromKitware** [comment]
Alright, I've put access to the problematic variables behind an `__attribute__((no_sanitize("thread")))` attribute. Local testing looks good.

**Pull request merged**
